2021-12-29 12:59:49.118 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (2092), thread 'MainThread' (139750478002480):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7f1a2ef86a60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7f1a2eb30dc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7f1a2eb30ee0>
    └ <function Scaffold.run at 0x7f1a2ea49430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7f1a2ea49430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7f1a2fb9ac40>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7f1a2ef845e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7f1a2efcaee0>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7f1a2efca5e0>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7f1a2efca670>
               └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7f1a2efca700>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7f1a2efca8b0>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7f1a2efc9160>
              └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7f1a2ea47fd0>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
2021-12-29 13:06:36.905 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (1951), thread 'MainThread' (140441749584176):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7fbb21f7ba60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7fbb21b25dc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7fbb21b25ee0>
    └ <function Scaffold.run at 0x7fbb21a3e430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7fbb21a3e430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7fbb22b8db20>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7fbb21f795e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7fbb21fbfee0>
           └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7fbb21fbf5e0>
           └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7fbb21fbf670>
               └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7fbb21fbf700>
           └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7fbb21fbf8b0>
           └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7fbb21fbe160>
              └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7fbb21a3cd60>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
2021-12-29 13:12:02.956 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (2151), thread 'MainThread' (140484411164976):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7fc510cbea60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7fc51086adc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7fc51086aee0>
    └ <function Scaffold.run at 0x7fc51077f430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7fc51077f430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7fc5118d2d00>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7fc510cbc5e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7fc510d01ee0>
           └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7fc510d015e0>
           └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7fc510d01670>
               └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7fc510d01700>
           └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7fc510d018b0>
           └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7fc510d00160>
              └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7fc51077df70>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
2021-12-29 14:50:13.292 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (1922), thread 'MainThread' (140662242650416):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7fee7860fa60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7fee781badc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7fee781baee0>
    └ <function Scaffold.run at 0x7fee780d1430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7fee780d1430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7fee79b46a90>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7fee7860d5e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7fee78652ee0>
           └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7fee786525e0>
           └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7fee78652670>
               └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7fee78652700>
           └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7fee786528b0>
           └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7fee78651160>
              └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7fee780cff10>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
2021-12-29 14:52:04.393 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (2093), thread 'MainThread' (140586310777136):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7fdcca7c7a60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7fdcca371dc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7fdcca371ee0>
    └ <function Scaffold.run at 0x7fdcca28a430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7fdcca28a430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7fdccbd50fd0>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7fdcca7c55e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7fdcca80bee0>
           └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7fdcca80b5e0>
           └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7fdcca80b670>
               └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7fdcca80b700>
           └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7fdcca80b8b0>
           └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7fdcca80a160>
              └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7fdcca288f40>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
2023-12-09 08:42:47.572 | ERROR    | __main__:handle_html:66 - Expecting value: line 1 column 1 (char 0)
2023-12-09 08:42:47.642 | ERROR    | __main__:handle_html:66 - Expecting value: line 1 column 1 (char 0)
2023-12-09 21:03:08.723 | ERROR    | __main__:handle_html:66 - Expecting value: line 1 column 1 (char 0)
2024-04-29 14:03:38.089 | ERROR    | fire.core:_CallAndUpdateTrace:693 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (2080), thread 'MainThread' (139719405219456):
Traceback (most recent call last):

  File "main.py", line 383, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7f12f4ab3820>

  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7f12f47a1040>
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7f12f47a1160>
    └ <function Scaffold.run at 0x7f12f473cc10>
> File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7f12f473cc10>

  File "main.py", line 372, in run
    template_ = booster.overload_tasks()
                │       └ <function CoroutineSpeedup.overload_tasks at 0x7f12f47405e0>
                └ <__main__.CoroutineSpeedup object at 0x7f12f4690b80>

  File "main.py", line 200, in overload_tasks
    md_obj: dict = ot.to_markdown(context)
                   │  │           └ {'paper': {'2404.17546': {'publish_time': '**2024-04-26**', 'title': '**Probabilistic Inference in Language Models via Twiste...
                   │  └ <function _OverloadTasks.to_markdown at 0x7f12f4740040>
                   └ <__main__._OverloadTasks object at 0x7f12f13d4820>

  File "main.py", line 335, in to_markdown
    _abstracts_md = f"\n#### Abstracts\n"+"".join([self._generate_markdown_abstract_content(
                                                   │    └ <function _OverloadTasks._generate_markdown_abstract_content at 0x7f12f4740310>
                                                   └ <__main__._OverloadTasks object at 0x7f12f13d4820>

  File "main.py", line 335, in <listcomp>
    _abstracts_md = f"\n#### Abstracts\n"+"".join([self._generate_markdown_abstract_content(
                                                   │    └ <function _OverloadTasks._generate_markdown_abstract_content at 0x7f12f4740310>
                                                   └ <__main__._OverloadTasks object at 0x7f12f13d4820>

  File "main.py", line 260, in _generate_markdown_abstract_content
    line = f"##### {paper['id']}" \

NameError: name 'paper_summary' is not defined
2024-04-29 14:30:08.044 | ERROR    | fire.core:_CallAndUpdateTrace:693 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (2086), thread 'MainThread' (140345751286976):
Traceback (most recent call last):

  File "main.py", line 386, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7fa4c9ba4790>

  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7fa4c988ef70>
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7fa4c98910d0>
    └ <function Scaffold.run at 0x7fa4c982ec10>
> File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7fa4c982ec10>

  File "main.py", line 375, in run
    template_ = booster.overload_tasks()
                │       └ <function CoroutineSpeedup.overload_tasks at 0x7fa4c98325e0>
                └ <__main__.CoroutineSpeedup object at 0x7fa4c9801c70>

  File "main.py", line 203, in overload_tasks
    md_obj: dict = ot.to_markdown(context)
                   │  │           └ {'paper': {'2404.17546': {'publish_time': '**2024-04-26**', 'title': '**Probabilistic Inference in Language Models via Twiste...
                   │  └ <function _OverloadTasks.to_markdown at 0x7fa4c9832040>
                   └ <__main__._OverloadTasks object at 0x7fa4c96be3d0>

  File "main.py", line 338, in to_markdown
    _abstracts_md = f"\n#### Abstracts\n"+"".join([self._generate_markdown_abstract_content(
                                                   │    └ <function _OverloadTasks._generate_markdown_abstract_content at 0x7fa4c9832310>
                                                   └ <__main__._OverloadTasks object at 0x7fa4c96be3d0>

  File "main.py", line 338, in <listcomp>
    _abstracts_md = f"\n#### Abstracts\n"+"".join([self._generate_markdown_abstract_content(
                                                   │    └ <function _OverloadTasks._generate_markdown_abstract_content at 0x7fa4c9832310>
                                                   └ <__main__._OverloadTasks object at 0x7fa4c96be3d0>

  File "main.py", line 263, in _generate_markdown_abstract_content
    line = f"##### {paper['id']}" \

NameError: name 'paper_summary' is not defined
2024-04-29 14:37:15.511 | ERROR    | fire.core:_CallAndUpdateTrace:693 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (2097), thread 'MainThread' (140315501352960):
Traceback (most recent call last):

  File "main.py", line 386, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7f9dbebbc790>

  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7f9dbe866f70>
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7f9dbe8690d0>
    └ <function Scaffold.run at 0x7f9dbe806c10>
> File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7f9dbe806c10>

  File "main.py", line 375, in run
    template_ = booster.overload_tasks()
                │       └ <function CoroutineSpeedup.overload_tasks at 0x7f9dbe80a5e0>
                └ <__main__.CoroutineSpeedup object at 0x7f9dbe7d9c70>

  File "main.py", line 203, in overload_tasks
    md_obj: dict = ot.to_markdown(context)
                   │  │           └ {'paper': {'2404.16957': {'publish_time': '**2024-04-25**', 'title': '**Attributing Responsibility in AI-Induced Incidents: A...
                   │  └ <function _OverloadTasks.to_markdown at 0x7f9dbe80a040>
                   └ <__main__._OverloadTasks object at 0x7f9dbc49e790>

  File "main.py", line 338, in to_markdown
    _abstracts_md = "\n#### Abstracts\n" + "".join([self._generate_markdown_abstract_content(
                                                    │    └ <function _OverloadTasks._generate_markdown_abstract_content at 0x7f9dbe80a310>
                                                    └ <__main__._OverloadTasks object at 0x7f9dbc49e790>

  File "main.py", line 338, in <listcomp>
    _abstracts_md = "\n#### Abstracts\n" + "".join([self._generate_markdown_abstract_content(
                                                    │    └ <function _OverloadTasks._generate_markdown_abstract_content at 0x7f9dbe80a310>
                                                    └ <__main__._OverloadTasks object at 0x7f9dbc49e790>

  File "main.py", line 263, in _generate_markdown_abstract_content
    line = f"##### {paper['id']}" \

NameError: name 'paper_summary' is not defined
2024-05-03 20:53:57.470 | ERROR    | __main__:handle_html:66 - Expecting value: line 1 column 1 (char 0)
2024-05-03 20:54:08.125 | ERROR    | __main__:handle_html:66 - Expecting value: line 1 column 1 (char 0)
2024-05-08 08:42:33.287 | ERROR    | fire.core:_CallAndUpdateTrace:693 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (2172), thread 'MainThread' (139983292922560):
Traceback (most recent call last):

  File "/home/runner/work/arxiv-daily-in-place/arxiv-daily-in-place/main.py", line 418, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7f5065801f30>

  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(verbose=False, interactive=False, separator='-', completion=None, help=False, trace=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7f50657aa290>
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7f50657aa3b0>
    └ <function Scaffold.run at 0x7f5063b1d510>
> File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7f5063b1d510>

  File "/home/runner/work/arxiv-daily-in-place/arxiv-daily-in-place/main.py", line 407, in run
    template_ = booster.overload_tasks()
                │       └ <function CoroutineSpeedup.overload_tasks at 0x7f5063b1dea0>
                └ <__main__.CoroutineSpeedup object at 0x7f5063b54cd0>

  File "/home/runner/work/arxiv-daily-in-place/arxiv-daily-in-place/main.py", line 237, in overload_tasks
    md_obj: dict = ot.to_markdown(context)
                   │  │           └ {'paper': {'2405.03689': {'publish_time': '**2024-05-06**', 'title': '**Pose Priors from Language Models**', 'paper_summary':...
                   │  └ <function _OverloadTasks.to_markdown at 0x7f5063b1d900>
                   └ <__main__._OverloadTasks object at 0x7f5063b57640>

  File "/home/runner/work/arxiv-daily-in-place/arxiv-daily-in-place/main.py", line 370, in to_markdown
    _abstracts_md = "\n#### Abstracts\n" + "".join([self._generate_markdown_abstract_content(
                                                    │    └ <function _OverloadTasks._generate_markdown_abstract_content at 0x7f5063b1dbd0>
                                                    └ <__main__._OverloadTasks object at 0x7f5063b57640>

  File "/home/runner/work/arxiv-daily-in-place/arxiv-daily-in-place/main.py", line 370, in <listcomp>
    _abstracts_md = "\n#### Abstracts\n" + "".join([self._generate_markdown_abstract_content(
                                                    │    └ <function _OverloadTasks._generate_markdown_abstract_content at 0x7f5063b1dbd0>
                                                    └ <__main__._OverloadTasks object at 0x7f5063b57640>

  File "/home/runner/work/arxiv-daily-in-place/arxiv-daily-in-place/main.py", line 299, in _generate_markdown_abstract_content
    f"\n{paper['paper_summary']}\n\n摘要：{paper['paper_summary_zh']}\n\n"

KeyError: 'paper_summary_zh'
2025-07-25 09:22:21.636 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-25 09:22:21.807 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-25 09:22:21.915 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-25 09:22:21.917 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-25 20:35:31.659 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-25 20:35:31.785 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-25 20:35:31.787 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-25 20:35:31.788 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-26 09:20:29.700 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-26 09:20:29.844 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-26 09:20:29.848 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-26 09:20:29.850 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-26 20:32:06.139 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-26 20:32:06.309 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-26 20:32:06.312 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-26 20:32:06.313 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-27 09:38:46.101 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-27 09:38:46.223 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-27 09:38:46.226 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-27 09:38:46.229 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-27 20:33:09.088 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-27 20:33:09.280 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-27 20:33:09.282 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-27 20:33:09.283 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-28 09:27:45.427 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-28 09:27:45.545 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-28 09:27:45.549 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-28 09:27:45.763 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-28 20:37:09.224 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-28 20:37:09.341 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-28 20:37:09.343 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-28 20:37:09.345 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-29 09:42:11.430 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-29 09:42:11.556 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-29 09:42:11.619 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-29 09:42:11.621 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-29 20:37:40.794 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-29 20:37:41.027 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-29 20:37:41.090 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-29 20:37:41.092 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-30 09:24:23.080 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-30 09:24:23.285 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-30 09:24:23.288 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-30 09:24:23.291 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-30 20:36:51.056 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-30 20:36:51.243 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-30 20:36:51.246 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-30 20:36:51.248 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-31 09:23:52.098 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-31 09:23:52.308 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-31 09:23:52.310 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-31 09:23:52.312 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-31 20:35:16.139 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-31 20:35:16.343 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-31 20:35:16.346 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-07-31 20:35:16.348 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-01 09:42:15.351 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-01 09:42:15.832 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-01 09:42:15.919 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-01 09:42:16.083 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-01 20:36:15.398 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-01 20:36:15.664 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-01 20:36:15.754 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-01 20:36:15.756 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-02 09:20:26.442 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-02 09:20:30.546 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-02 09:20:30.548 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-02 09:20:30.550 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-02 20:32:51.292 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-02 20:32:51.423 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-02 20:32:51.427 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-02 20:32:51.429 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-03 09:40:06.677 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-03 09:40:06.799 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-03 09:40:06.883 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-03 09:40:07.639 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-03 20:34:05.389 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-03 20:34:05.533 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-03 20:34:05.616 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-03 20:34:05.618 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-04 09:40:14.419 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-04 09:40:14.541 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-04 09:40:14.660 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-04 09:40:14.664 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-04 20:38:13.179 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-04 20:38:13.305 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-04 20:38:13.307 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-04 20:38:13.310 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-05 09:25:58.540 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-05 09:25:58.665 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-05 09:25:58.667 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-05 09:25:58.669 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-05 20:37:49.475 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-05 20:37:49.635 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-05 20:37:49.637 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-05 20:37:49.639 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-06 09:24:23.610 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-06 09:24:23.734 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-06 09:24:23.737 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-06 09:24:23.874 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-06 20:37:41.230 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-06 20:37:41.366 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-06 20:37:41.368 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-06 20:37:41.370 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-07 09:24:53.023 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-07 09:24:53.175 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-07 09:24:53.178 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
2025-08-07 09:24:53.180 | ERROR    | __main__:handle_html:116 - Expecting value: line 3 column 1 (char 2)
